// Code generated by mockery v1.0.0. DO NOT EDIT.

package poll

import (

	mock "github.com/stretchr/testify/mock"

	"flow/models"
)

// FakeWfRunPoller is an autogenerated mock type for the WfRunPoller type
type FakeWfRunPoller struct {
	mock.Mock
}

// Poll provides a mock function with given fields: runID
func (_m *FakeWfRunPoller) Poll(runID string) (models.WorkflowRun, error) {
	ret := _m.Called(runID)

	var r0 models.WorkflowRun
	if rf, ok := ret.Get(0).(func(string) models.WorkflowRun); ok {
		r0 = rf(runID)
	} else {
		r0 = ret.Get(0).(models.WorkflowRun)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(runID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
